config/routes.rb
require 'resque/server'
Lending::Application.routes.draw do

  resources :items do
    collection do
      get :item_history, :show_waiting
    end
  end

  resources :seats do
    collection do
      get :update_status, :reset_seat
    end
  end

  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords", :confirmations => "confirmations"}
  devise_scope :user do
    get "admins", to: "sessions#new", :role => "admin"
  end
  root :to => 'home#index'

  mount ChinaCity::Engine => '/china_city'

  mount Resque::Server, :at => "/resque"

  #mount MongodbLogger::Server.new, :at => "/system_logger", :as => :mongodb
  #mount MongodbLogger::Assets.instance, :at => "/system_logger/assets", :as => :mongodb_assets # assets

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin?) && current_user.is_admin?
  end

  constraints resque_web_constraint do
    ResqueWeb::Engine.eager_load!
    mount ResqueWeb::Engine => "/resque_web"
  end

  devise_scope :user do
    resources :registrations do
      collection do
        get :validate_captcha
      end
    end
  end

  # 我要理财
  resources :invests do
    collection do
      get :search
      get :info_json
      get :search_json
      get 'show_invest', 'show_rookie_invest'
      get :rookie_new
      post :create_rookie_bid
    end
  end

  # 债权转让
  resources :debts do
    collection do
      get :debt_json
      get :show_debts
    end
  end


  # 收益计算器
  get 'calculator', to: 'invests#calculator'

  # 我要借款
  get 'loan', to: 'loans#new'

  # 用户来源
  get 'source', to: 'home#source'
  get 'users_source', to: 'home#users_source'

  get 'campaign/:id' => 'campaigns#static'

  namespace :account do

    # 我的账户
    resource :users do
      # 个人主页
      get :show
      get :show_json

      # 实名认证
      get :real_name
      put :request_auth_realname

      # 手机认证
      get :auth_phone

      get :auth_email
      post :confirmation

      # 发送验证码
      get :send_verify_code

      # 验证手机号
      post :verify_phone

      # 个人设置
      get :profile

      get :show_set_password
      get :show_set_trade_password

      post :set_password
      post :set_trade_password
    end

    # 交易记录
    get 'transactions', to: 'cash_flows#index'

    # 充值
    get 'recharge', to: 'pay_orders#new'
    resources :recharges, controller: 'pay_orders' do
      collection do
        get :offline_recharge, :index_offline
        post :create_offline_recharge
      end
      # post 'recharge', to: 'pay_orders#create'

      # # 充值记录
      # get 'recharges', to: 'pay_orders#index'
    end

    # 提现
    resources :withdraws

    # 银行卡管理
    resources :banks, controller: 'user_banks'

    # 理财管理
    resources :invests, controller: 'bids' do
      collection do
        get :stat # 理财统计
        get :repaying
        get :finished
        get :rookie
      end
      member do
        get :contract, :print_contract
      end
    end

    resources :debts do
      collection do
        get :selling_list
        get :sold
      end

      member do
        get :sell
        put :hawk
        put :cancel_hawk
      end
    end

    # 自动投标
    resources :auto_invests

    # 收款明细
    resources :collections

    #协议
    resources :contracts

    #站内消息
    resources :messages

    # 邀请管理
    resources :promotions do
      collection do
        #转盘抽奖结果
        get :circle, :egg, :box, :lucky_code, :lucky_guess, :newyear_egg
        get :spring
        get :two_yr_anniversary
        get :cash, :actual_object, :bribery_money
      end
    end

    #一元购
    resources :yiyuangous do
      collection do
        get :progressing, :waiting, :finished
      end
    end

  end
  namespace :user do
    get 'finish_payment/:id/:pay_class/:notice_from', to: 'payments#finish'
    post 'finish_payment/:id/:pay_class/:notice_from', to: 'payments#finish'
  end
  resources :home, except: [:show] do
    collection do
      get :company_info
      get :info_json
      get :basic_info_json
      get :banner_info
      get :send_verify_code2
      get :confirm_email
      get :source
    end
  end
  resources :guides
  resources :helps
  resources :loan_applications

  resources :webnews

  resources :downloads

  resources :campaigns do
    collection do
      get :circle, :circle_prize, :online, :august, :anniversary, :anniversary_report
      get :september, :anti_japanese, :anti_api, :zhongqiu, :zhongqiu_start, :zhongqiu_end, :zhongqiu_fail
      get :october, :november, :guanggun, :december, :apponline, :double12
      get :lucky_code, :lucky_guess, :huodong_comment, :annual_celebration, :newyear_egg, :newyear_egg_api
      post :update_lucky_code, :create_lucky_guess, :create_huodong_comment
      get :hd20160101
      get :two_yr_anniversary, :two_yr_circle_prize, :two_yr_aug_camp
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :banners do
    end
    resources :users
    resources :cash_flows do
      collection do
        get :bids, :repaying, :finished, :stat
      end
    end
    resources :loans do
      collection do
        get :newest
      end
    end
    get "home", to: "home#index"

    devise_scope :user do
      resources :registrations do
        collection do
          get :send_verify_code, :verify_code, :validate_captcha, :verify_mobile
        end
      end
      post "sessions", to: "sessions#create"
      get "sessions/logout", to: "sessions#logout"
    end

    resources :recharges do
      collection do
        get :online_records, :offline_records, :show_banks
        post :create_offline_recharge, :withdraw
        get :withdraw_record, :show_account_bank, :user_info
      end
    end

  end

end

app/controllers/api/home_controller.rb
class Api::HomeController < Api::BaseController

  skip_before_action :ajax_requests_required

  ##
  #
  # 最新的标
  #
  def index
    @loan = Loan.bidding_or_after.order('available_amount desc, id desc').where("pass = ''").first
    @info = {
      id: @loan.id,
      invest_amount: (Loan.total_amount + 95366700).to_i,
      interest_amount: (Collection.sum(:interest) + 1999200).to_i,
      process: @loan.progress,
      interest: @loan.interest,
      months: @loan.months,
      available_amount: @loan.available_amount,
      title: @loan.title[0, 15]
    }


    # render 'layouts/api', layout: false
  end

end

app/controllers/backend/home_controller.rb
# encoding: utf-8

class Backend::HomeController < Backend::BaseController

  def index
    if current_user.source.present? || current_user.channel.present?
      redirect_to branch_backend_lenders_path
    end
  end

end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
  # include ApplicationHelper
  # 网站首页
  def index
    #A
    @area_a = Seat.a
    @area_a_total = {}
    @area_a.each do |a|
      if @area_a_total[a.row].blank?
        @area_a_total[a.row] = {}
        @area_a_total[a.row][:col] = []
        @area_a_total[a.row][:amount] = 0
        a.num =~ /^(.+)-/
        @area_a_total[a.row][:prefix] = $1
      end
      @area_a_total[a.row][:col] << a
      @area_a_total[a.row][:amount] += 1
    end
    @area_a_count = @area_a.count
    @area_a_reserve = @area_a.reserve.count
    @area_a_sold = @area_a.sold.count
    @area_a_idle = @area_a.idle.count
    #B1
    @area_b1 = Seat.b1
    @area_b1_total = {}
    @area_b1.each do |b|
      if @area_b1_total[b.row].blank?
        @area_b1_total[b.row] = {}
        @area_b1_total[b.row][:col] = []
        @area_b1_total[b.row][:amount] = 0
        b.num =~ /^(.+)-/
        @area_b1_total[b.row][:prefix] = $1
      end
      @area_b1_total[b.row][:col] << b
      @area_b1_total[b.row][:amount] += 1
    end
    @area_b1_count = @area_b1.count
    @area_b1_reserve = @area_b1.reserve.count
    @area_b1_sold = @area_b1.sold.count
    @area_b1_idle = @area_b1.idle.count
    #B2
    @area_b2 = Seat.b2
    @area_b2_total = {}
    @area_b2.each do |b|
      if @area_b2_total[b.row].blank?
        @area_b2_total[b.row] = {}
        @area_b2_total[b.row][:col] = []
        @area_b2_total[b.row][:amount] = 0
        b.num =~ /^(.+)-/
        @area_b2_total[b.row][:prefix] = $1
      end
      @area_b2_total[b.row][:col] << b
      @area_b2_total[b.row][:amount] += 1
    end
    @area_b2_count = @area_b2.count
    @area_b2_reserve = @area_b2.reserve.count
    @area_b2_sold = @area_b2.sold.count
    @area_b2_idle = @area_b2.idle.count
    #C
    @area_c = Seat.c
    @area_c_total = {}
    @area_c.each do |c|
      if @area_c_total[c.row].blank?
        @area_c_total[c.row] = {}
        @area_c_total[c.row][:col] = []
        @area_c_total[c.row][:amount] = 0
        c.num =~ /^(.+)-/
        @area_c_total[c.row][:prefix] = $1
      end
      @area_c_total[c.row][:col] << c
      @area_c_total[c.row][:amount] += 1
    end
    @area_c_count = @area_c.count
    @area_c_reserve = @area_c.reserve.count
    @area_c_sold = @area_c.sold.count
    @area_c_idle = @area_c.idle.count
    #D
    @area_d = Seat.d
    @area_d_total = {}
    @area_d.each do |d|
      if @area_d_total[d.row].blank?
        @area_d_total[d.row] = {}
        @area_d_total[d.row][:col] = []
        @area_d_total[d.row][:amount] = 0
        d.num =~ /^(.+)-/
        @area_d_total[d.row][:prefix] = $1
      end
      @area_d_total[d.row][:col] << d
      @area_d_total[d.row][:amount] += 1
    end
    @area_d_count = @area_d.count
    @area_d_reserve = @area_d.reserve.count
    @area_d_sold = @area_d.sold.count
    @area_d_idle = @area_d.idle.count
    #E
    @area_e = Seat.e
    @area_e_total = {}
    @area_e.each do |e|
      if @area_e_total[e.row].blank?
        @area_e_total[e.row] = {}
        @area_e_total[e.row][:col] = []
        @area_e_total[e.row][:amount] = 0
        e.num =~ /^(.+)-/
        @area_e_total[e.row][:prefix] = $1
      end
      @area_e_total[e.row][:col] << e
      @area_e_total[e.row][:amount] += 1
    end
    @area_e_count = @area_e.count
    @area_e_reserve = @area_e.reserve.count
    @area_e_sold = @area_e.sold.count
    @area_e_idle = @area_e.idle.count
  end

  def show
    render :show_new, :layout=> "account"
  end

  # 公司简介
  def company_info
  end
  # banner
  def banner_info
    banners = Banner.display.for_pc
    respond_to do |format|
      format.json do
        render json: banners.to_json
      end
    end
  end

  def info_json
    loans = Loan.bidding_or_after.order('available_amount desc, id desc').limit(6)
    loan_infos = {}
    loans.each_with_index do |loan, index|
      loan_infos.merge!((index.to_s).to_sym => {id: loan.id, amount: loan.amount, state: loan.state.name, title: loan.title[0, 16], name: loan.borrower.name[0, 8], progress: loan.progress, interest: loan.interest, month: loan.months})
    end

    articles = {}
    Article.select('id, title').notice.limit(5).each_with_index do |article, index|
      articles.merge!(index.to_s.to_sym => {id: article.id, title: article.title[0,14]})
    end

    fabiaos = {}
    Article.select('id, title').fabiao.limit(5).each_with_index do |article, index|
      fabiaos.merge!(index.to_s.to_sym => {id: article.id, title: article.title})
    end

    friendlinks = Friendlink.order("id desc").limit(7)

    #新增新手标
    rookie_item = RookieLoan.can_be_invest.first

    info = {
            invest_people: User.lender.count + 9503,
            invest_amount: rmb_wan(Loan.total_amount + 95366700),
            interest_amount: rmb_wan(Collection.sum(:interest) + 1999200),
            loans: loan_infos,
            notices: articles,
            fabiaos: fabiaos,
            friendlinks: friendlinks,
            rookie_item: rookie_item
          }
    respond_to do |format|
      format.json do
        render json: info.to_json
      end
    end
  end

  def basic_info_json
    info = {company_name: SystemConfig.company_name.value,
            phone400: SystemConfig.phone400.value,
            serve_time: SystemConfig.serve_time.value,
            qq_server: SystemConfig.qq_server.value,
            qq_group: SystemConfig.qq_group.value,
            prize_register: SystemConfig.prize_register_amount.value.to_s + '元',
            prize_first: SystemConfig.prize_first_amount.value.to_s + '元',
            promotion_ratio: SystemConfig.promotion_ratio.value.to_s + '%',
            username: current_user.try(:username).to_s
          }
    respond_to do |format|
      format.json do
        render json: info.to_json
      end
    end
  end

  def send_verify_code2
    if params[:captcha].blank? || !simple_captcha_valid?
      render :text => 'captcha error'
      return
    end
    if User.where(:mobile  => params[:mobile]).count == 0
      # 生成验证码
      verify_code = 1001 + rand(8980)

      # 发送验证码
      redis = Redis.new
      redis.set params[:mobile], verify_code
      redis.expire params[:mobile], 120

      res = Resque.enqueue(SmsJob, :send_verify_code, params[:mobile], verify_code)
      render :text => res
    else
      render :text => 'false'
    end
  end

  def confirm_email
    user = User.find_by_confirmation_token params[:confirmation_token]
    if user.present? && user.confirmed_at.blank?
      # user.update_attribute(:confirmed_at, Time.now)
      user.confirm!
    elsif user.present? && user.confirmed_at.present?
      flash[:errors] = '该邮箱已通过验证。'
    else
      flash[:errors] = '邮箱验证失败，请重新验证。'
    end
    if current_user.present?
      redirect_to auth_email_account_users_path
    else
      redirect_to new_user_session_path
    end
  end

  def source
    cookies[:source] = params[:source_id1] if params[:source_id1].present?
    cookies[:channel] = params[:source_id2] if params[:source_id2].present?
    render nothing: true
  end

  def users_source
    if params[:sourcexxx].present?
      @users = User.reorder('id desc').where(:source => params[:sourcexxx]).paginate :page => params[:page], :per_page => 1000
      render layout: false
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
	
end

app/views/home/_bid.haml
- l =loan
.col-sm-12.hover-effect{:style => "padding:0px;"}
  .box
    .box-content.bid
      .row
        .col-sm-2
          .box{:style => "margin:0px;"}
            .box-content.avatar
              %img.img-responsive{:alt => "Account", :src => "#{bid_avatar_url(l)}"}
        .col-sm-10.no-padding
          .row
            .col-sm-6
              %h4
                %a.dimgray{:href => invest_path(l), :target => "_blank", :title => l.title}= l.title
            .col-sm-3
              - if l.with_mortgage?
                %label.btn.btn-warning.btn-sm{:style=>"border:none;"} 抵押
              - if l.with_guarantee?
                %label.btn.btn-success.btn-sm{:style=>"border:none;"} 担保
          .row
            .col-sm-3
              %ul.list-unstyled.bid_list
                %li
                  借款金额：
                  %span.text-big.num.text-right
                    %em.value= bid_amount l.amount
                    元
                %li
                  信用等级：
                  %span.fn-right.text-right
                    %a{:class => "creditlevel #{l.try(:credit_level).try(:upcase)} snow"}= l.try(:credit_level).try(:upcase)
            .col-sm-3
              %ul.list-unstyled.bid_list
                %li
                  年利率：
                  %span.text-big.num
                    %em.value= l.interest
                    \%
                %li
                  已完成：
                  .fn-right.progress{:style => "line-height:20px;width:90px;margin:6px;"}
                    .progress-bar.progress-bar-success{:style => "width:#{l.progress}%;#{l.progress < 40 ? 'color:#000;' : ''}"}
                      = l.progress.to_s+"%"
            .col-sm-3
              %ul.list-unstyled.bid_list
                %li
                  贷款期限：
                  %span.text-big.num.text-right
                    %em.value= l.months
                    个月
                %li
                  还款方式：
                  = t(l.repay_style)
            .col-sm-3
              = loan_state l

app/views/home/banner_info.html.erb
<header>
  <div class="header-content home">
    <div class="parallax-bg" id="slider-wrap">
    <div class="slider parallax-bg" id="slider"> 
      <div class="slider-sections sandbox"> 
        <% @banners.each do |banner| %>
        <section> <img src="<%= banner.pic.url %>" alt="Kendo UI" style="width:100%; margin:0;" />
        </section>
        <% end %>
      </div> 
    </div> <a class="slider-prev" href="javascript: void(0)">?</a> <a class="slider-next" href="javascript: void(0)">?</a>
    </div>
  </div>
</header>
<script type='text/javascript' src='js/common.js'></script>
<script type='text/javascript' src='js/slider.js'></script>

app/views/home/company_info.haml
.wrapped-content{:style => "min-height: 400px;"}
  .col-xs-12
    = render "/layouts/news_nav_left"
    %section#content{:style => "margin-top: 20px;"}
      .container
        .row.recent-activity
          .box.col-xs-12
            .box-header.blue-background
              .title 公司简介
            .box-content
              %p xxxxxxxxxxxxxxxxx，系xxxxxxxxxxxxxxxxxxxxxxxxxxxxx创办。
              %p 自xxxx年xx月成立至今，xxx的服务已覆盖了全国30余个省的2000多个地区，服务了几十万名客户，成功帮助他们通过信用申请获得融资借款，或通过自主出借获得稳定收益。
              %p 作为中国最早的一批基于互联网的P2P信用借贷服务平台，xxx以其诚信、透明、公平、高效、创新的特征赢得了良好的用户口碑。现在，xxx已成为行业内最具影响力的品牌之一。
              %h3 使命
              %p 实现个人的信用自主和金融自由。
              %h3 愿景
              %p 打造一个人人参与、人人自由、人人平等的互联网个人金融服务平台。
              %h3 核心价值
              %dl
                %dt 释放用户借款和理财的自主权利
                %dd 借款人通过个人信用申请借款，获得资金；理财人通过公开信息自主选择进行投资，获得收益。
                %dt.mt10 建立互联网时代的个人金融风险定价体系
                %dd 通过有效的个人信用模型和大数据挖掘，逐步建立并完善符合时代特征的个人金融风险定价体系。
                %dt.mt10 实现更低借款成本和更稳健投资收益
                %dd
                  受益于精准的个人金融风险定价体系和安全分散有保障的投资机制，借款人和理财人的权益均可得到充分的
                  %br 保障和满足。

app/views/home/indexbk.html.erb
<style type="text/css">
  .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
  background-color: #FBFBFB;
  }
</style>
<div id="fb-root" class=" fb_reset">
<!--
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to '登录', '/users/sign_in'  %>
<%= link_to '退出', destroy_user_session_path, :method => :delete %>-->
<a name="top"></a>
<div id="index" data-spy="scroll">
    <div class="banner">
      <ul>
        <% @banners.each do |banner|%>
        <li style="background-image: url('<%= banner.pic.url%>');">
          <div class="inner">
          <%= banner.inner_html.html_safe%>
<!--             <h1>国内领先的P2P网贷平台</h1>
            <p>低风险、高收益、零费率</p>

            <a class="ban_btn" href="#">开始投资</a> -->
          </div>
        </li>
        <% end%>
      </ul>
    </div>

<div id="faq" class="wrapped-content">
  <div class="grid-row clearfix">
    <div class="grid-3">
      <div class="big-icon-plane"></div><h3>投资理财</h3>
      成为理财人后，预期12%-14%的年化收益轻松实现。
    </div>
    <div class="grid-3">
      <div class="big-icon-heart"></div><h3>本金保障</h3>
      所有理财用户的每笔出借资金均在本金保障计划覆盖之内，一旦出现逾期坏账，风险备用金优先垫付，保证理财人的资金安全。
    </div>
    <div class="grid-3">
      <div class="big-icon-wrench"></div><h3>低门槛</h3>
      50元起步，0手续费
    </div>
  </div>
</div>

<div class="hr"></div>
<div class="wrapped-content">
  <div class='col-sm-12' style="padding:0px;">
    <div class="box">
      <div class="box-content">
        <div class="row">
          <div class="col-sm-2">
            <div class="box" style="margin:0px;">
              <div class="box-content">
                <img alt="Account" class="img-responsive" src="/assets/account.gif">
              </div>
            </div>
          </div>
          <div class="col-sm-10">
            <div class="form-group">
              <div class="col-sm-10">
              <h4>借款人装修房子贷款啊，赶紧投标</h4>
              </div>
            </div>
            <div>
              <div class="col-sm-3">
                <ul class="list-unstyled bid_list">
                  <li >
                    借款金额：<span class="text-big num text-right"><em class="value">100000.0</em>元</span>
                  </li>
                  <li>
                    信用等级：<span class="fn-right text-right"><a class="creditlevel A snow">A</a></span>
                  </li>
                </ul>
              </div>

              <div class="col-sm-3">
                <ul class="list-unstyled bid_list">
                  <li >
                    年利率：<span class="text-big num"><em class="value">13.0</em>%</span>
                  </li>
                  <li>
                    已完成：

                        <div class="fn-right progress" style="line-height:20px;width:90px;margin:6px;">
                          <div class="progress-bar progress-bar-success" style="width:60%;">60%</div>
                        </div>

                  </li>
                </ul>
              </div>

              <div class="col-sm-3">
                <ul class="list-unstyled bid_list">
                  <li >
                    贷款期限：<span class="text-big num text-right"><em class="value">10</em>个月</span>
                  </li>
                  <li>
                    还款方式：等额本息
                  </li>
                </ul>
              </div>

            </div>
            <div class="col-sm-3">
              <a href="/invests/14" class="btn btn-primary btn-block btn-lg">投标</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class='tabbable'>
      <ul class='nav nav-tabs'>
        <li class='active'>
          <a data-toggle='tab' href='#tab1'>
            <h3>投资列表</h3>
          </a>
        </li>
        <li>
          <a data-toggle='tab' href='#tab2'>
            <h3>预计发标</h3>
          </a>
        </li>
      </ul>
      <div class='tab-content'>
        <div class='tab-pane active' id='tab1'>
          <table class="table table-hover table-list text-big">
            <thead>
              <tr>
                <th>借款标题</th>
                <th>信用等级</th>
                <th>年利率</th>
                <th>金额</th>
                <th>期限</th>
                <th>进度</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |l| %>
                <tr>
                  <td>
                    <span class="fn-left text-big">
                      <!--<em class="loantype fn-left" title="信用认证标"></em>-->
                      <a class="fn-left dimgray" href="<%= invest_path(l) %>" target="_blank" title="<%= l.title %>"><%= l.title %></a>
                    </span>
                  </td>
                  <td>
                    <span class="fn-left"><a class="creditlevel <%= l.try(:credit_level).try(:upcase) %> snow"><%= l.try(:credit_level).try(:upcase) %></a></span>
                  </td>
                  <td>
                    <span class="fn-left text-big num"><em class="value"><%= l.interest %></em>%</span>
                  </td>
                  <td>
                    <span class="fn-left text-big num text-right"><em class="value"><%= l.amount %></em>元</span>
                  </td>
                  <td>
                    <span class="fn-left text-big num text-right"><em class="value"><%= l.months %></em>个月</span>
                  </td>
                  <td>
                    <div class="progress progress-striped active invest-process">
                      <div class="progress-bar progress-bar-success " role="progressbar" aria-valuenow="<%= l.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= l.progress %>%">
                        <span class="sr-only"><%= l.progress %>% Complete (success)</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <%= loan_state l %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td colspan="7" class="text-center">
                <a class="darkgray" href="<%= invests_path %>" target="_blank"><strong>查看更多</strong></a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class='tab-pane' id='tab2'>
          <table class="table table-hover table-list text-big">
            <thead>
              <tr>
                <th>借款标题</th>
                <th>信用等级</th>
                <th>年利率</th>
                <th>金额</th>
                <th>期限</th>
                <th>进度</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @loans_feature.each do |l| %>
                <tr>
                  <td>
                    <span class="fn-left text-big">
                      <!--<em class="loantype fn-left" title="信用认证标"></em>-->
                      <a class="fn-left dimgray" href="<%= invest_path(l) %>" target="_blank" title="<%= l.title %>"><%= l.title %></a>
                    </span>
                  </td>
                  <td>
                    <span class="fn-left"><a class="creditlevel <%= l.try(:credit_level).try(:upcase) %> snow"><%= l.try(:credit_level).try(:upcase) %></a></span>
                  </td>
                  <td>
                    <span class="fn-left text-big num"><em class="value"><%= l.interest %></em>%</span>
                  </td>
                  <td>
                    <span class="fn-left text-big num text-right"><em class="value"><%= l.amount %></em>元</span>
                  </td>
                  <td>
                    <span class="fn-left text-big num text-right"><em class="value"><%= l.months %></em>个月</span>
                  </td>
                  <td>
                    <div class="progress progress-striped active invest-process">
                      <div class="progress-bar progress-bar-success " role="progressbar" aria-valuenow="<%= l.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= l.progress %>%">
                        <span class="sr-only"><%= l.progress %>% Complete (success)</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <%= loan_state l %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td colspan="7" class="text-center">
                <a class="darkgray" href="<%= invests_path %>" target="_blank"><strong>查看更多</strong></a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="hangyenewsbox">
          <div class="hychild">
            <% @medias.each do |media| %>
              <div class="hangyenews">
                <p class="hyp"><span class="hyspan"><%= media.name %></span></p>
                  <ul id="news-list" class="hangul">
                    <% media.articles.first(4).each do |article| %>
                      <li><a target="_blank" class="f16" href="<%= webnews_path(article) %>"><p class="decoration mt18"></p><%= article.title %></a></li>
                    <% end %>
                  </ul>
                  <p class="news-list-more"><a class="darkgray f16" href="<%= webnews_index_path(:st => media.id) %>">查看更多</a></p>
              </div>
            <% end %>

            </div><!--hychild -->
        </div>
</div>
</div>

<script src="/assets/unslider.js"></script>
<script>
  $(function() {
    $('.banner').unslider({
        fluid: true,
        dots: true
    });
});
</script>